// src/components/header.tsx
'use client'
import { forwardRef, HTMLAttributes } from 'react'

import { LennyFace } from './lenny-face'

interface HeaderProps extends HTMLAttributes<HTMLElement> {
  isFullscreen: boolean
  toggleFullscreen: () => void
}

export const Header = forwardRef<HTMLDivElement, HeaderProps>(({ isFullscreen, toggleFullscreen, ...props }, ref) => {
  return (
    <header
      className={`relative flex items-center justify-between px-4 py-3 cursor-default overflow-hidden ${isFullscreen ? 'lg:cursor-pointer' : 'lg:cursor-grab lg:active:cursor-grabbing'}`}
      ref={ref}
      {...props}
    >
      <div className='absolute lg:flex items-center top-1/2 -translate-y-1/2 group hidden'>
        <button className='h-6 w-6 rounded-full grid place-items-center' onClick={() => window.close()} aria-label='Close'>
          <div className='h-3 w-3 rounded-full bg-[#898989] group-hover:bg-[#FF6057] transition-colors' />
        </button>
        <button className='h-6 w-6 rounded-full grid place-items-center' aria-label='Minimize'>
          <div className='h-3 w-3 rounded-full bg-[#898989] group-hover:bg-[#FEBC2D] transition-colors' />
        </button>
        <button className='h-6 w-6 rounded-full grid place-items-center' onClick={toggleFullscreen} aria-label='Maximize'>
          <div className='h-3 w-3 rounded-full bg-[#898989] group-hover:bg-[#2BC840] transition-colors' />
        </button>
      </div>
      <p className='mx-auto select-none font-semibold not-sr-only hidden lg:block'>Alacritty</p>
      <p className='mx-auto select-none font-semibold not-sr-only lg:hidden block'>Wiscaksono</p>
      <LennyFace />
    </header>
  )
})

// src/lib/components/layout/header/header.svelte
<script lang="ts">
	import Face from './face.svelte';

	interface $$Props {
		isFullscreen: boolean;
		onMouseDown: (e: MouseEvent) => void;
		toggleFullscreen: () => void;
	}

	let { isFullscreen, onMouseDown, toggleFullscreen }: $$Props = $props();

	function handleHeaderKeyDown(event: KeyboardEvent) {
		if (event.key === 'Enter' || event.key === ' ') {
			event.preventDefault();
			toggleFullscreen();
		}
	}
</script>

<!-- svelte-ignore a11y_no_static_element_interactions -->
<header
	class={`relative flex cursor-default items-center justify-between overflow-hidden px-4 py-3 ${isFullscreen ? 'lg:cursor-pointer' : 'lg:cursor-grab lg:active:cursor-grabbing'}`}
	ondblclick={toggleFullscreen}
	onmousedown={onMouseDown}
	onkeydown={handleHeaderKeyDown}
>
	<div class="group absolute top-1/2 hidden -translate-y-1/2 items-center lg:flex">
		<button class="grid h-6 w-6 place-items-center rounded-full" onclick={() => window.close()} aria-label="Close">
			<div class="h-3 w-3 rounded-full bg-[#898989] transition-colors group-hover:bg-[#FF6057]"></div>
		</button>
		<button class="grid h-6 w-6 place-items-center rounded-full" aria-label="Minimize">
			<div class="h-3 w-3 rounded-full bg-[#898989] transition-colors group-hover:bg-[#FEBC2D]"></div>
		</button>
		<button class="grid h-6 w-6 place-items-center rounded-full" onclick={toggleFullscreen} aria-label={isFullscreen ? 'Exit Fullscreen' : 'Enter Fullscreen'}>
			<div class="h-3 w-3 rounded-full bg-[#898989] transition-colors group-hover:bg-[#2BC840]"></div>
		</button>
	</div>
	<p class="not-sr-only mx-auto hidden font-semibold select-none lg:block">Ghostty</p>
	<p class="not-sr-only mx-auto block font-semibold select-none lg:hidden">Wiscaksono</p>
	<Face />
</header>
